/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282180
 */
public class MedicoPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicoPanel
     */
    public MedicoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollEspecialidades = new javax.swing.JScrollPane();
        tableEspecialidade = new javax.swing.JTable();
        ButtonDelete = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonCriar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        setLayout(null);

        tableEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        tableEspecialidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEspecialidade.getTableHeader().setReorderingAllowed(false);
        ScrollEspecialidades.setViewportView(tableEspecialidade);

        add(ScrollEspecialidades);
        ScrollEspecialidades.setBounds(10, 20, 960, 280);

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/delete32.png"))); // NOI18N
        ButtonDelete.setToolTipText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        add(ButtonDelete);
        ButtonDelete.setBounds(760, 310, 50, 40);

        ButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/Lapis1.png"))); // NOI18N
        ButtonEditar.setToolTipText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });
        add(ButtonEditar);
        ButtonEditar.setBounds(820, 310, 50, 40);

        ButtonCriar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/plus32.png"))); // NOI18N
        ButtonCriar.setToolTipText("Criar Especialidade");
        ButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCriarActionPerformed(evt);
            }
        });
        add(ButtonCriar);
        ButtonCriar.setBounds(880, 310, 50, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed

        if(getLinha() != -1){
            excluirEspecialidade();
        }else {
            JOptionPane.showMessageDialog(
                this,
                "Selecione a especialidade qe você deseja exculuir",
                "Atenção",
                JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed

        if(getLinha() != -1) {
            editarEspecialidade();
        }else{
            JOptionPane.showMessageDialog(this,
                "Por favor, selecione a especialidade que você deseja editar.",
                "Especialidade",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCriarActionPerformed
        EspecialidadeDialog especialidadeDialog =
        new EspecialidadeDialog(null, true, OperacaoEnum.ADICIONAR);
        especialidadeDialog.setVisible(true);
        preencherTabela();
    }//GEN-LAST:event_ButtonCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCriar;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JScrollPane ScrollEspecialidades;
    private javax.swing.JTable tableEspecialidade;
    // End of variables declaration//GEN-END:variables
}
