/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira;

import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 22282180
 */
public class ClinicaFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClinicaFrame
     */
    public ClinicaFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/imagem/Calendar.png")));
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelDeTitulo = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        LabelCalendario = new javax.swing.JLabel();
        ButtonAgenda = new javax.swing.JButton();
        ButtonPaciente = new javax.swing.JButton();
        ButtonMédicos = new javax.swing.JButton();
        ButtonEspecialidade = new javax.swing.JButton();
        ButtonPlanoSaude = new javax.swing.JButton();
        PainelEspecialidade = new javax.swing.JPanel();
        ScrollEspecialidades = new javax.swing.JScrollPane();
        TableEspecialidade = new javax.swing.JTable();
        ButtonEditar = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonCriar = new javax.swing.JButton();
        ButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento");
        setBackground(new java.awt.Color(150, 150, 150));
        setResizable(false);
        getContentPane().setLayout(null);

        PainelDeTitulo.setBackground(new java.awt.Color(0, 16, 33));
        PainelDeTitulo.setLayout(null);

        LabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(23, 114, 255));
        LabelTitulo.setText("Agenda de Consultas ");
        PainelDeTitulo.add(LabelTitulo);
        LabelTitulo.setBounds(80, 20, 270, 28);

        LabelCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/Calendar.png"))); // NOI18N
        LabelCalendario.setText("jLabel3");
        PainelDeTitulo.add(LabelCalendario);
        LabelCalendario.setBounds(10, 0, 70, 70);

        getContentPane().add(PainelDeTitulo);
        PainelDeTitulo.setBounds(0, 0, 1000, 80);

        ButtonAgenda.setBackground(new java.awt.Color(54, 202, 210));
        ButtonAgenda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonAgenda.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/ImagemCalendar_1.png"))); // NOI18N
        ButtonAgenda.setText("Agenda");
        ButtonAgenda.setToolTipText("Agenda");
        ButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAgenda);
        ButtonAgenda.setBounds(10, 100, 110, 27);

        ButtonPaciente.setBackground(new java.awt.Color(54, 202, 210));
        ButtonPaciente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonPaciente.setForeground(new java.awt.Color(0, 0, 0));
        ButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/Paciente.png"))); // NOI18N
        ButtonPaciente.setText("Paciente");
        ButtonPaciente.setToolTipText("Paciente");
        ButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPaciente);
        ButtonPaciente.setBounds(130, 100, 110, 27);

        ButtonMédicos.setBackground(new java.awt.Color(54, 202, 210));
        ButtonMédicos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonMédicos.setForeground(new java.awt.Color(0, 0, 0));
        ButtonMédicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/doctor.png"))); // NOI18N
        ButtonMédicos.setText("Médicos");
        ButtonMédicos.setToolTipText("Médicos");
        ButtonMédicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMédicosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMédicos);
        ButtonMédicos.setBounds(250, 100, 110, 27);

        ButtonEspecialidade.setBackground(new java.awt.Color(54, 202, 210));
        ButtonEspecialidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonEspecialidade.setForeground(new java.awt.Color(0, 0, 0));
        ButtonEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/stethoscope.png"))); // NOI18N
        ButtonEspecialidade.setText("Especialidade");
        ButtonEspecialidade.setToolTipText("Especialidade");
        ButtonEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEspecialidadeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEspecialidade);
        ButtonEspecialidade.setBounds(370, 100, 140, 27);

        ButtonPlanoSaude.setBackground(new java.awt.Color(54, 202, 210));
        ButtonPlanoSaude.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonPlanoSaude.setForeground(new java.awt.Color(0, 0, 0));
        ButtonPlanoSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/badge.png"))); // NOI18N
        ButtonPlanoSaude.setText("Plano de Saúde");
        ButtonPlanoSaude.setToolTipText("Plano de Saúde");
        ButtonPlanoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlanoSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlanoSaude);
        ButtonPlanoSaude.setBounds(520, 100, 150, 27);

        PainelEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        PainelEspecialidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidades Medicas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(24, 0, 255))); // NOI18N
        PainelEspecialidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PainelEspecialidade.setOpaque(false);
        PainelEspecialidade.setLayout(null);

        TableEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        TableEspecialidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollEspecialidades.setViewportView(TableEspecialidade);

        PainelEspecialidade.add(ScrollEspecialidades);
        ScrollEspecialidades.setBounds(10, 20, 960, 290);

        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/Lapis1.png"))); // NOI18N
        ButtonEditar.setToolTipText("Editar");
        PainelEspecialidade.add(ButtonEditar);
        ButtonEditar.setBounds(850, 330, 50, 40);

        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/delete32.png"))); // NOI18N
        ButtonDelete.setToolTipText("Delete");
        PainelEspecialidade.add(ButtonDelete);
        ButtonDelete.setBounds(780, 330, 50, 40);

        ButtonCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/plus32.png"))); // NOI18N
        ButtonCriar.setToolTipText("Criar Especialidade");
        PainelEspecialidade.add(ButtonCriar);
        ButtonCriar.setBounds(920, 330, 50, 40);

        getContentPane().add(PainelEspecialidade);
        PainelEspecialidade.setBounds(10, 150, 980, 390);

        ButtonSair.setBackground(new java.awt.Color(54, 202, 210));
        ButtonSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonSair.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagem/logout32.png"))); // NOI18N
        ButtonSair.setText("Sair");
        ButtonSair.setToolTipText("Sair");
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSair);
        ButtonSair.setBounds(870, 100, 120, 30);

        jPanel1.setBackground(new java.awt.Color(165, 165, 165));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 1000, 510);

        setSize(new java.awt.Dimension(1016, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAgendaActionPerformed

    private void ButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPacienteActionPerformed

    private void ButtonMédicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMédicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMédicosActionPerformed

    private void ButtonEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEspecialidadeActionPerformed

    private void ButtonPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPlanoSaudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgenda;
    private javax.swing.JButton ButtonCriar;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonEspecialidade;
    private javax.swing.JButton ButtonMédicos;
    private javax.swing.JButton ButtonPaciente;
    private javax.swing.JButton ButtonPlanoSaude;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JLabel LabelCalendario;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PainelDeTitulo;
    private javax.swing.JPanel PainelEspecialidade;
    private javax.swing.JScrollPane ScrollEspecialidades;
    private javax.swing.JTable TableEspecialidade;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela(){
        
        String[][] dados = {
            {"100", "Jandira", "SP"},
            {"200", "Itapevi", "SP"},
            {"300", "Cotia", "SP"},
            {"400", "Barueri", "SP"},
            {"500", "Curitiba", "PR"},
            {"600", "Fortaleza", "CE"},
        };
    
        String[] titulos = {"Código", "Nome das cidades", "Estados"};
        
        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        
        TableEspecialidade.setModel(modelo);
        
    }

}
